server:
  port: 8080
  servlet:
    context-path: /employee_management


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employees_management
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver